<?php
echo Phalcon\Tag::form(
    [
        "signup/findlogin",
        "method" => "post",
    ]
);
?>
<!-- Email input -->
<div class="form-outline mb-4">
    <input name='email' type="email" id="form2Example1" class="form-control" />
    <label class="form-label" for="form2Example1">
        <?php echo $this->locale->_("Email address") ?>
    </label>
</div>

<!-- Password input -->
<div class="form-outline mb-4">
    <input name='password' type="password" id="form2Example2" class="form-control" />
    <label class="form-label" for="form2Example2">
        <?php echo $this->locale->_("Password") ?>
    </label>
</div>

<!-- Submit button -->
<button type="submit" class="btn btn-primary btn-block mb-4">
    <?php echo $this->locale->_("Sign in") ?>
</button>
</div>
<?php echo $this->tag->linkTo(
    ['/signup/', $this->locale->_('SignUp Instead'), 'class' => $class]
);
?>
</form>