<?php include_once(APP_PATH.'/views/header.php'); ?>
<h1>List of All Users</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">User Id</th>
            <th scope="col">E-mail</th>
            <th scope="col">Password</th>
            <th scope ='col'>Role</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <?php echo $message ?>
    </tbody>
</table>
