<?php include_once(APP_PATH . '/views/header.php');
?>
<h1>Settings</h1>
<?php echo $this->tag->form("/setting/"); ?>
<p>
    <label for="title">Choose Title</label>
    <select name="title" id="title">
        <option value="with-tag">With Tags</option>
        <option value="without-tag">Without Tags</option>
    </select>
</p>
<p>
    <label for="default-price">Default Price</label>
    <?php echo $this->tag->textField("defaultPrice"); ?>
</p>
<p>
    <label for="default-stock">Default Quantity</label>
    <?php echo $this->tag->textField("defaultQuantity"); ?>
</p>
<p>
    <label for="default-zip">Default Price</label>
    <?php echo $this->tag->textField("defaultPrice"); ?>
</p>
<p>
    <?php echo $this->tag->submitButton("Save Settings"); ?>
</p>
</form>
